### ISSUE TITLE
Clean deprectaed, serializer, etc - leave only inspector code.

### ISSUE THREAD

**Issue by ajboni** [vexe/VFW#109]
Hi Vexe! I have been using vfw for a few years in my engine, mostly for the inspector goodies, Im about to start working on a new project, and im thinking what would it take to clean all deprecated and old serializer code and leave only inspector related stuff.
Do you think its feasible? Thanks, rodo

**Comment by DoomT-AliW** [comment]
Hey there! IIRC, all the deprecated stuff in "VFW Deprecated" you should be able to just delete with no issues whatsoever. Did you get any errors when doing so?

**Comment by ajboni** [comment]
Hi! Sorry for the delay. IIRC fastsave was giving me problem, but I will start a new project soon and test it out. Thank you!
