### ISSUE TITLE
uAction causing DelegateDrawer error

### ISSUE THREAD

**Issue by colms** [vexe/VFW#14]
I have an uAction happen when a projectile knocks into something. I added the action the first time and it worked as expected. Then just by pressing stop and play again, the UI went a little [crazy](http://i.imgur.com/eVHFK4y.png) and lots of errors came up. Restarting the editor didn't fix it. Nor did reinstalling the Vexe unitypackage.

Here are some of the code involved (it depends on so much I didn't want to put it all here):

``` csharp
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine.Events;
using Vexe.Runtime.Types;


    public class ProjectileShell : BetterBehaviour
    {
        public uAction<Projectile, Collision2D, CombatCharacter> Collided;

        public void Collide(Projectile projectile, Collision2D collision, CombatCharacter shotBy)
        {
            Collided.Invoke(projectile, collision, shotBy);
            OnCollided(projectile, collision, shotBy);
        }

        protected virtual void OnCollided(Projectile projectile, Collision2D collision,
            CombatCharacter shotBy) { }
    }

    public class SimpleProjectileGenerator : ProjectileGenerator
    {
        [SerializeField] GameObject projectile_;

        public void GenerateFromProjectileCollision(Projectile projectile, Collision2D collision, CombatCharacter shotBy)
        {
            print("generating from collision");

            Projectile p = Instantiate(projectile_).GetComponent<Projectile>();
            p.Init(projectile.transform.position, projectile.transform.rotation, shotBy);
        }
    }
```

This is really low priority because you made UnityEvent work so I can just use that until this is fixed. If you get stuck trying to reproduce this I could send you the code for my game.

**Comment by vexe** [comment]
I see what is causing it to happen (a method is null from one of the handlers). But I don't see why would that happen. Yes send me a small project replicating this please.

**Comment by colms** [comment]
I haven't been able to reproduce it on a smal scale yet. I'll work on it.

**Comment by colms** [comment]
I found one of the errors. Really simple but just not what I expected. I just have to initialize the uAction like this in the Awake function:

``` csharp
void Awake()
{
    Collided = new uAction<Projectile, Collision2D, CombatCharacter>()
}
```

Is there any way I could just have the uAction auto initialized so I don't have to worry about it?

**Comment by vexe** [comment]
You don't need to do it in Awake, in fact you shouldn't do it like that. Cause then it will be reinitialized when you run the game overwriting whatever values you set in the editor. You should check if it's null instead. A better place would be to initialize it immediately when you declare it. If you leave it uninitialized, delegate drawer will initialize it for you but only when the drawer is active. i.e. if you add this script in runtime from code, well, there's no drawers so it will be null.

**Comment by colms** [comment]
I can't reproduce the bug since I removed the component and added it again. I must've done something funky. Anyway, I'm happy enough to say that this was probably something strange I was doing rather than a framework problem. I was messing around with different versions of VFW so maybe I had some files from an old version mixed with a new one or something even though I thought I clean reinstalled. I'm happy to close this issue.

Thanks for the advice on the event initialization!
