### ISSUE TITLE
Redundancy/repetitiveness/duplicate code when having members with similar formatting/annotations

### ISSUE THREAD

**Issue by vexe** [vexe/VFW#18]
Take a look at the following:

![clutter](https://cloud.githubusercontent.com/assets/1978827/7795814/3ae6a752-028d-11e5-948e-bcaf3f57b084.png)

This really doesn't look good. Having to duplicate all those notations and format methods, just clutters the code. Also those null checks in the formatters, why do I have to care about null? I just want to return the format of my member. Not cool.

Possible solutions:
1- Considering that most the current usages of FormatMethod is to display the count of collections, can't we have that as an option in the collection display options itself? (i.e. Dict.ShowCount or Seq.ShowCount) - Also, having the collection type be between prens beside its name is useful, but not as useful as seeing the count. Maybe we should just display the count by default? and let showing the type be an option?

2- Since we can inject attributes in members/drawers, is there no way to 'externally' annotate members? like, don't explicitly tag them with attributes and end up with that clutter, but just a more organized way, hmmm....

Thanks :D

**Comment by vexe** [comment]
This seems like a step in the right direction, Importing/reusing attributes! - The editor is still a bit verbose than one might need. I'll work on that next.

![clutter](https://cloud.githubusercontent.com/assets/1978827/7797281/e013ca82-029e-11e5-8940-e0e27535179e.png)

**Comment by vexe** [comment]
Mucho better... :)

![using](https://cloud.githubusercontent.com/assets/1978827/7804848/cfd78706-031d-11e5-9449-a9bb014ea899.png)

**Comment by vexe** [comment]
Mucho better... :)

![using](https://cloud.githubusercontent.com/assets/1978827/7804867/12642052-031e-11e5-8337-4ae5a338ead6.png)

**Comment by vexe** [comment]
Mucho better ... :)

![using](https://cloud.githubusercontent.com/assets/1978827/7804890/5bcb3b9a-031e-11e5-865b-fe3264b6f2d4.png)

**Comment by Xelnath** [comment]
Nicely done.
