### ISSUE TITLE
ShowTypeAttribute and Monobehaviours

### ISSUE THREAD

**Issue by panickbr** [vexe/VFW#30]
First, let me tell you what I'm doing (trying to).

Instead of creating a prefab for each "potion", I created a class and stored every variant in a ScriptableObject.

Anyway, consider this snippet.

``` csharp
[ShowType(typeof(APickupScript))]
public Type ComponentScript { get; private set; }
```

This is what happens:

![image](https://cloud.githubusercontent.com/assets/5217864/8344575/bdc6e666-1ab9-11e5-9be4-dc9ea1def45f.png)

It currently shows MonoBehaviour, Component, Object, etc. Classes that APickupScript inherits from, and not only classes that inherit from APickupScript. What is happening here?

The other method (just using `public APickupScript ComponentScript` doesn't work, as Unity thinks I want to reference a Monobehaviour itself, not just "reference" it's type. (Which is intended).

Edit: I must make it clear that using a Abstract "common" (not Monobehaviour) class works fine.

I don't have any object using the component in my scene, and I don't need (want) to have it, otherwise I would be doing a prefab for every potion anyway.

Is this intended? Is it not a problem with VFW itself?

Thank you!

**Comment by vexe** [comment]
Hey!

My current local master branch is a bit messy so I won't commit this one, but it's pretty simple.

Go to ReflectionHelper.cs line 135, method GetAllUnityEngineTypesOf and change "type.IsA" to "type.IsAssignableFrom" - That should fix it!

**Comment by panickbr** [comment]
Perfect.

Thank you again! Keep up the good work.
