### ISSUE TITLE
VFW and Editor class

### ISSUE THREAD

**Issue by bartlomiejwolk** [vexe/VFW#31]
Can I use both VFW and have an editor class for the same script? Like when I need editor only for the _OnSceneGUI()_ but I want to display values in the inspector with VFW.

**Comment by vexe** [comment]
Sure, just inherit BetterBehaviourEditor. If you need to do something extra in the editor gui, don't override OnInspectorGUI, instead override OnGUI, if you want the base gui, call base.OnGUI. If you just need OnSceneGUI stuff you don't need to mess with anything just write your OnSceneGUI

**Comment by bartlomiejwolk** [comment]
thx :)
