### ISSUE TITLE
Multiselect LayerMask dropdown

### ISSUE THREAD

**Issue by bartlomiejwolk** [vexe/VFW#32]
I know that the answer may be somewhere in the documentation and video tutorials but just now I don't have time to go through them.

The question is, how to draw multiselect LayerMask dropdown?

When I do:

```
[SerializeField]
private LayerMask layerMask;
```

I get only a single choice dropdown:

![screenshot_19](https://cloud.githubusercontent.com/assets/325348/8413080/4619b994-1e8e-11e5-9ce7-23e89d0f0275.png)

**Comment by vexe** [comment]
Annotate with [EnumMask]

-- Edit, sorry not that one. Let me remember...

**Comment by bartlomiejwolk** [comment]
I did it like this:

```
   [SerializeField]
        [EnumMask]
        private LayerMask layerMask;
```

and I have this error:

_Drawer `EnumMaskDrawer` can't seem to handle type `LayerMask`. Make sure you're not applying attributes on the wrong members_

**Comment by vexe** [comment]
Right. It's fixed in the version I'm using now, but now the one currently in master. I'll try to pull an update as soon as I can. You shouldn't need to annotate with anything. EnumMask gives you multiple options if you apply it on an enum, not a layer mask.

**Comment by bartlomiejwolk** [comment]
ok, thx

**Comment by vexe** [comment]
https://github.com/vexe/VFW/commit/6456fe35acf8d5b9cc629b24a43a04e5feb4bdeb
