### ISSUE TITLE
Error when using UnityEvent

### ISSUE THREAD

**Issue by bartlomiejwolk** [vexe/VFW#33]
When I create a field like this:

```
  [SerializeField]
        private UnityEvent callbacks;
```

set it up in the inspector and the enter and exit play mode, I get this error and the _UnityEvent_ field disappears from the inspector.

![screenshot_20](https://cloud.githubusercontent.com/assets/325348/8413452/d3445354-1e90-11e5-8902-e627c1f4c0aa.png)

**Comment by vexe** [comment]
Not sure, it seems like an internal unity thing. The relevant part is BaseEditor.DoUnityLayout line 192 - even If I do "if (serializedObject == null) return;" it would throw while getting the value of the object.

**Comment by bartlomiejwolk** [comment]
Maybe it's because I'm using the Asset Store version?

**Comment by vexe** [comment]
You mean the .unitypackage? No it's the same

**Comment by bartlomiejwolk** [comment]
yeah, my bad. I meant the unity package.

**Comment by vexe** [comment]
Working in this framework for a long time made me familiar with all these weird bugs. Fix will be included in next version, in the meantime I don't want you to wait, here's how you fix it:
- Got to BaseEditor.cs
- In OnInspectorGUI, remove those 3 lines:
  
  ```
      var rabbit = gui as RabbitGUI;
      if (rabbit != null && rabbit.OnFinishedLayoutReserve == null && _membersDrawnByUnityLayout.Length > 0)
          rabbit.OnFinishedLayoutReserve = DoUnityLayout;
  ```
- Go up to OnEnable, right after the call to Initialize() add these lines:
  
  ```
      var rabbit = gui as RabbitGUI;
      if (rabbit != null && _membersDrawnByUnityLayout.Length > 0)
          rabbit.OnFinishedLayoutReserve = DoUnityLayout;
  ```

**Comment by bartlomiejwolk** [comment]
It works. Thanks for help, it's really appreciated.
