### ISSUE TITLE
How to activate game object from uDelegate?

### ISSUE THREAD

**Issue by bartlomiejwolk** [vexe/VFW#34]
In _UnityEvent_, when I reference a game object, I can select _GameObject_ and the _SetActive()_ to either activate or deactivate the game object. It's really usefull but _uDelegate_ seem to not have this option?

![screenshot_22](https://cloud.githubusercontent.com/assets/325348/8416715/d2b32bf6-1ea7-11e5-8938-f8bdf800568c.png)

**Comment by vexe** [comment]
Are you talking about gameObject.SetActive in particular?

**Comment by bartlomiejwolk** [comment]
yeah, but also other methods and properties in the _GameObject_.

**Comment by vexe** [comment]
Go to DelegateDrawer.cs, change the function calls in the lines (might have slightly different numbers) 236 and 506 from: GetAllComponents to GetAllComponentsIncludingSelf - That will include the gameObject in the list of targets.

**Comment by bartlomiejwolk** [comment]
It works, thx. Will this change be included in the next release? I would really want that.

**Comment by vexe** [comment]
Sure
