### ISSUE TITLE
GC allocation problem on instantiate

### ISSUE THREAD

**Issue by bartlomiejwolk** [vexe/VFW#35]
When I instantiate prefabs, quite a lot of data is allocated.

![screenshot_26](https://cloud.githubusercontent.com/assets/325348/8435230/718d844e-1f50-11e5-81c5-df0b95de0d1e.png)

For some reason _BetterBehaviour_ shows up in the inspector. The instantiated prefabs have _BetterBehaviour_ scripts attached.

![screenshot_25](https://cloud.githubusercontent.com/assets/325348/8435258/9cafb142-1f50-11e5-99ab-f7816950d767.png)

Can it be that I'm doing something wrong when using _BetterBehaviours_?

**Comment by vexe** [comment]
There is no way around that. FullSerializer is slow. In the next version you could inherit from BaseBehaviour, which would give you all the editor power of VFW but comes with the default Unity serialization. I came to the conclusion that the best serialization system to persist data between edit-playmode is Unity's (even though we give it a lot of flak), all the other systems are flawed. I've been suffering with these slowness and gc issues myself https://github.com/vexe/VFW/issues/25 the best way is just to work with Unity's default serialization, it's fast, reliable and covers most use cases.

**Comment by bartlomiejwolk** [comment]
I think I can live with that in the editor but the main problem I have is that it slows down my web exported project to a crawl (only when instantiating prefabs). Shouldn't this slowdown be happening only in the editor?

**Comment by vexe** [comment]
No. OnBeforeSerialize gets called when cloning/instantiating too
http://blogs.unity3d.com/2014/06/24/serialization-in-unity/ - Why don't you
pool your objects? (Instantiate them once, and keep them around, disabled.
When you need one, get the first disabled one, enable it and reset its
state)

**Comment by bartlomiejwolk** [comment]
So, is this framework really applicable for performance intensive games? Even if all game objects were instantiated when the game loads (and this is likely to take some time), the GC will then collect them during the game play causing significant performance decrease. I'm not an expert, just want to better understand what VFW is best for.

**Comment by bartlomiejwolk** [comment]
I don't think when I write. Obviously, pooled object won't be garbage collected.

**Comment by vexe** [comment]
The best advice I could give you is to use BaseBehaviour (https://github.com/vexe/VFW/commit/f1a52d87c03e8acd51c2eb14fd3501015dd75285) wherever possible (has 0 runtime penalty) and just stick to Unity's serialization, and workaround it if you need to. Custom serialization is either slow, or not robust/stable. Also use pooling :)
