### ISSUE TITLE
StringExtensions.ToTitleCase

### ISSUE THREAD

**Issue by ajboni** [vexe/VFW#37]
Hello!
It seems this method is conflicting with $nicename.

```
     public static string ToTitleCase(this string input)
        {
            input = input.ToLower().Replace("_", " ");
            TextInfo info = CultureInfo.CurrentCulture.TextInfo;
            input = info.ToTitleCase(input).Replace(" ", string.Empty);
            return input;
        }
```

![2015-07-01 23_48_57-unity personal 64bit - vicraider unity - uae - web player_ _dx11_](https://cloud.githubusercontent.com/assets/12578313/8469138/0c2a8f96-204c-11e5-8deb-3943e0ddd076.jpg)

commenting those three lines, fixes the problem. Its related to regional settings in any way? (latin american system)

![2015-07-01 23_52_19-unity personal 64bit - vicraider unity - uae - web player_ _dx11_](https://cloud.githubusercontent.com/assets/12578313/8469157/47ef0f16-204c-11e5-9894-63e25f355280.jpg)

**Comment by vexe** [comment]
What is the actual name of the field? "notificationTime"? or?

**Comment by ajboni** [comment]
yup, notificationTime, just tested, and the same output as picture 1 (Notificationtime) with these four: 

```
        public float notificationTime;
        public float NotificationTime;
        public float _Notificationtime;
        public float notificationtime;
```

**Comment by vexe** [comment]
Insert this:

```
                if (name.IsPrefix("m_"))
                    result = name.Remove(0, 1);
                else result = name;

                var builder = new StringBuilder();
                for(int i = 0; i < result.Length; i++)
                {
                    var current = result[i];
                    if (current == '_' && i + 1 < result.Length)
                    {
                        var next = result[i + 1];
                        if (char.IsLower(next))
                            next = char.ToUpper(next);
                        builder.Append(next);
                        i++;
                    }
                    else
                        builder.Append(current);
                }

                result = builder.ToString();
```

Code should look like this http://i.imgur.com/QALrLFK.png

This should fix it. I'll push to master in a bit.

**Comment by ajboni** [comment]
Perfect! That fixed ! Thanks!
