### ISSUE TITLE
Request: Drag and drop re-orderable lists?

### ISSUE THREAD

**Issue by tmunro** [vexe/VFW#40]
First off, great framework. It's taking a little bit for me to get used to it, but I'm discovering all kinds of great time savers.

I'd love to have draggable re-orderable list support, a la [Rotorz](https://bitbucket.org/rotorz/reorderable-list-editor-field-for-unity). I don't know if that's something that could be integrated in some way (not sure on that clause of the MIT license).

Also, while I'm here, is it possible to integrate the script name / enable checkbox that Unity draws with the script picker from VFW?

Thanks!

**Comment by vexe** [comment]
I don't have plans for re-orderable lists at the moment, you can give it a try yourself if you want, just look at SequenceDrawer.cs to see how I'm doing the element drawing. I guess the challenging thing would be to port rotorz to use Vfw's custom GUI layout system (Rabbit)

But imho it's more on the 'fancy' side than on the 'useful' one. - You could just use Display(Seq.Advanced), check the box and use the arrow buttons to move elements up/down, same effect but less fancy.

[Edit] Btw re-orderable lists are part of the public Unity editor API, code could be ripped easily.

I'm sorry I don't get your last question.

**Comment by tmunro** [comment]
I'll take a look at implementing the re-orderable list stuff - it's significantly more user friendly than up/down buttons because you can move an item to a precise position in a single movement.

My other question is basically about this part, whether the Unity script name and options line can be combined in some way with the MonoBehaviour picker:
[Link](https://www.dropbox.com/s/3ojrhzy5giyikjk/Screenshot%202015-07-09%2016.47.28.png?dl=0)

**Comment by vexe** [comment]
No I don't have control over that header. Btw you don't get the enabled checkbox unless you have an OnEnable function.

**Comment by tmunro** [comment]
Alright, thanks for the answers!
