### ISSUE TITLE
False positive on Dictionary PerItem Test

### ISSUE THREAD

**Issue by jonhartnett** [vexe/VFW#41]
The test in MemberDrawersHandler that ensures that the PerItem attribute is not applied incorrectly to a Dictionary does not first ensure that the PerItem attribute is one of the explicit members of either a PerKey or PerValue attribute. The relevent code is in the GetAppliedAttributes method on line 110.

**Comment by vexe** [comment]
Right. You could go crazy with those PerX, I wanted to keep it sane and simple. PerX are meant to be applied/used in relatively simpler scenarios. In more complex ones, It's better to use a custom drawer.
