### ISSUE TITLE
foldouts, key?

### ISSUE THREAD

**Issue by code-beans** [vexe/VFW#52]
Here is my situation
I try to implement a custom editor for **MyScript** that inherites from _BaseBehaviour_.
I wrote a customEditor that inherites from _BaseBehaviourEditor_ for MyScript.

MyScript holds and properly serizalizes a **List<MyOtherScript>**

In the _OnSceneGUI()_ in the customEditor of _MyScript_ I want to Debug some information for each instance in List<MyOtherScript> that is fold out in the inspector.

Now I know that I have the foldouts[key] property since I inherite from BaseBehaviourEditor. But what is the key for each of these Instances?

**Comment by vexe** [comment]
You want to control the folding for each of those MyOtherScript from your MyScript editor? - if that's the case, you need to access the foldout boolean values from the editor BetterPrefs asset which can be done via 'foldouts[id]' - You can get the 'id' via RuntimeHelper.GetTargetid(my_other_script) - See how the 'id' is assigned in BaseEditor.OnEnable

**Comment by code-beans** [comment]
I tried that, but it didnt work.

Here is a small UML CD to outline my basic code structure.

![umlcd](https://cloud.githubusercontent.com/assets/4446123/9154671/b32843ec-3e9c-11e5-9c91-60f11bc16b50.png)

``` c#
public void OnSceneGUI()
    {
        var node = target as TrafficNode;
        foreach (var lane in node.Lanes)
        {
            var id = RuntimeHelper.GetTargetID(lane);
            Debug.Log("The lane id is " + id);
            Debug.Log("The lane is fold out in the Inspector: " + foldouts[id]);
                        if(foldout[id]) {
                              //log information here
                        }
        }
    }
```

Each lane has a unique id.
But no matter what I do in the inspector the _foldout[id]_ value is always _false_.

I want to Debug some information in the scene if and only if the lane is foldout in the Inspector

**Comment by vexe** [comment]
Sorry I don't understand what's the problem. The foldouts will always be false unless you set them to true. I don't see you doing that anywhere in the code you posted. Are you sure MyOtherScript derives BaseBehaviour (or BetterBehaviour for that matter)?

**Comment by code-beans** [comment]
I guess my assumption is wrong.

I thought this to be in a _foldouts[laneId] == false_ state:
![foldout2](https://cloud.githubusercontent.com/assets/4446123/9154996/279f7450-3ea9-11e5-8752-660e48aa6aad.png)

And this to be in a _foldouts[laneId] == true_ state:
![foldout1](https://cloud.githubusercontent.com/assets/4446123/9155000/616532ba-3ea9-11e5-91b9-bc57b4e7aec1.png)

To clarify.
_MyScript_ would be the _TrafficNode_ that derives from BetterBehaviour
_MyOtherScript_ would be the _Lane_ 

I need the information which lanes in _trafficNode.Lanes_ are currently "fold out" in the Inspector.

**Comment by vexe** [comment]
Sorry forgot that the lanes are in a list. If you look at SequenceDrawer you'll see what the ids are foreach element. You'll find that it's RuntimeHelper.CombineHashCodes(id, index); where id is the drawer id, and index is the lane element index in the list/array. The id of the drawer is the same as the editor member id, if you go to editor member to see how it's calculated you'll find CombineHashCodes(targetId, TypeNiceName, DisplayText); where targetId is the id of the target being inspected (this is the id I previously mentioned to y0u, in BaseEditor.cs), TypeNiceName is the nice name of the lanes list/array (e.g. List<Lane>) and DisplayText is how the list/array is displayed in the inspector (e.g. Lanes (ELEMENT_COUNT)) - So you can see it's a bit hairy, I never actually thought someone would want to access those foldouts directly. I don't have an API where you can get the EditorMember wrapping a certain member, and then drill down the hierarchy to get to nested members, I never found a need to do it.

Is it so inconvenient to fold them out from the inspector?

Another approach, only works if the elements foldout keys exist in BetterEditorPrefs.asset is to set all the boolean keys in BetterPrefs.GetEditorInstance() to true but like I said the elements foldouts have to exist in the prefs asset first (i.e. you have to inspect the lanes list at least once)

**Comment by code-beans** [comment]
ok. As you said it's a bit hairy.

My initial goal was to somehow select a subset of trafficNode.Lanes for which I want to display additional information in the scene gui (Color highlighting, texts, etc.)

I thought to pick the ones that are fold out in the inspector already.
Now since that's off the list, I will figure out a way around it.
But anyways. Thanks for your support 

issue can be closed I guess.
