### ISSUE TITLE
Required attributes

### ISSUE THREAD

**Issue by krisrok** [vexe/VFW#53]
hi, i don't really get how the Required\* attributes are supposed to work. the resolvers are placed in "Assets/VFW Misc" and do not really belong to the core library? and i guess it's not the intended workflow to have Requirements.Resolve(this, gameObject); in every Start() method?

**Comment by vexe** [comment]
They were in the core, but I decided to move them out, so they're now an 'application' if you will. The way they're meant to be used is, say you have a script attached to a GameObject 'go' with this field:

[HasRequirements]
public class Test : MonoBehaviour
{
    [RequiredFromThis]
    public Transform trans;
}
The point is to have the field be automatically assigned to the Transform of 'go' - Now there's two ways you could resolve the requirements of a GameObject, automatic and manual. If you use this feature in the editor you'd probably want to go with automatic, which means resolve the requirements of all scripts annotated with [HasRequirements] even if their GameObjects are not selected. manual means you do it by yourself, like you said in Start or in some function triggered by an editor button (annotated with [Show]).

To turn on/off automatic resolution, use the menu items: Tools/Vexe/Requirements as far as I remember. I moved the system out of the core cause I felt it was a bit sketchy, it was an experiment. I now prefer to initialize my fields by hand in code in Awake/Start rather then clutter my fields with annotations and rely on another system that does the initialization for me. But you can give it a try, if you like it and it works, you can use it.

There's a RequirementsExample.cs I think somewhere in the VFWExamples folder you can check out too.

Hope that helps.

**Comment by krisrok** [comment]
ok, switched back to GetComponent<>() :)
