### ISSUE TITLE
Other Scripted Type Support

### ISSUE THREAD

**Issue by james7132** [vexe/VFW#58]
Unity recently added NetworkBehaviours and AnimationStateBehaviours. Both of which are incompatible with the current setup. Is there any plan to support these types?

AnimationStateBehaviours are relatively simple, since they inherit from ScriptableObject, and are otherwise just normal assets.

NetworkBehaviours derive from the normal MonoBehaviour, but the introduction of attributes like SyncVar and Command may not work well with how VFW currently works.

**Comment by vexe** [comment]
See my conversation with user maikklein VFW thread page 8 post 362
