### ISSUE TITLE
DefineCategories does not work with Subclasses

### ISSUE THREAD

**Issue by james7132** [vexe/VFW#62]
Categories defined in superclasses are not usable in subclasses until they are defined again on the subclass itself. For example:

```
[DefineCatergories("Tags", "Test")]
public class TestA {
    [Serialize, Tags, Category("Tags")]
    private string PlayerTag;
    ...
}

[DefineCategories("Tags")] //Without this line, categorization breaks
public lass TestB : TestA {
    [Serialize, Tags, Category("Tags")]
    private string EnemyTag
    ...
}
```

**Comment by vexe** [comment]
If I recall correctly the categorization stuff is only applicable for BaseBehaviours, not arbitrary System.Objects. So when you say Category("Tags") on a field inside a System.Object it will look for a Tags category on your Base/Better Behaviour. The resolver responsible for that is in CategoryDefinitionResolver.cs. Category could work with System.Objects but I thought it was a complexity that wasn't worth it.

**Comment by james7132** [comment]
Oh I forgot to make TestA a subclass of Base or BetterBehaviour in the
example, but the issue still happens when the type is a subclass of either.

**Comment by vexe** [comment]
Try passing 'true' to the two GetCustomAttribute calls in CategoryDefinitionResolver.cs line 31 and 35

**Comment by vexe** [comment]
@james7132 is the issue still on?
