### ISSUE TITLE
Editor won't prompt user to save changes made to BetterBehaviours

### ISSUE THREAD

**Issue by ArielSchoch** [vexe/VFW#7]
When closing a scene, Unity does not ask whether you would like to save the changes made to a BetterBehaviour component.
Before closing, you must therefor manually save the scene to make sure the changes will persist.

**Comment by vexe** [comment]
Forgot to mention it, but it's basically here (in EditorMember.cs) https://github.com/vexe/VFW/commit/67a465e786ea8d28053777f0f6aa7b9af8d1e01a#diff-a29d6c6ef9b42e9371cbcdbcc4ebb111 - I was registering Undo 'after' I make modifications, while it should be before.
