### ISSUE TITLE
EditorGUI.InspectorTitlebar takes 4 parameters in Unity5.3

### ISSUE THREAD

**Issue by hsandt** [vexe/VFW#73]
As I explained in [this post](http://forum.unity3d.com/threads/open-source-vfw-134-drawers-save-system-serialize-interfaces-generics-autoprops-delegates.266165/page-9#post-2421054), [EditorGUI.InspectorTitlebar](http://docs.unity3d.com/ScriptReference/EditorGUI.InspectorTitlebar.html) takes a 4th boolean parameter "expandable" in Unity5.3 so the method RabbitGUI.InspectorTitlebar in Vexe\GUIs\RabbitGUI\RabbitGUI.cs is not correct anymore and will prevent compilation with the error `No overload for method 'InspectorTitlebar' takes '3' arguments`.

As a quick fix I added "true" as a 4th argument since you probably want the property to be expandable, but it would make sense to add the same 4th argument to RabbitGUI.InspectorTitlebar and to pass it to EditorGUI.InspectorTitlebar. For backward compatibility, you could also add a default value:

`public override bool InspectorTitlebar(bool foldout, UnityObject target, bool expandable = true)`

I know the description of the issue is already close to a fix, but I'm not familiar with InspectorTitlebar, I just wanted my code to compile, so I let those who know better choose how to fix it.

**Comment by vexe** [comment]
The default bool expandable=true should be good. Have you had any issues with it? I'm kind of away from VFW codebase at the moment that's why I asked for a PR when you can.

**Comment by NakorTBR** [comment]
I didn't dig into the Unity API changes or anything but it looks like they removed the default on the bool value.  I did the same thing and used true.

**Comment by hsandt** [comment]
No problem so far, but I'll try both versions just in case and send a PR when I find the time. Sorry to keep you waiting a little more.

**Comment by hsandt** [comment]
@srndpty spotted the issue too and fixed it by adding true as 4th argument directly. I should thank him/her...

I think it was the only instance in VFW. If anyone needs more customization he/she can add a patch anytime.
