### ISSUE TITLE
Issue for Popup in BetterScriptableObject

### ISSUE THREAD

**Issue by YacineFenina** [vexe/VFW#78]
Hello,

I just notice a strange behavior for Popup.
When I have severale sheet of BetterScriptable object of the same subtype. 
if I change the value of one of this sheet, the other one will show the same value.

I looked in the OnChanged function but the new value assigned is the right one.

Do you have an Idea ?

**Comment by vexe** [comment]
Can you post the code you used to surface the issue?

**Comment by YacineFenina** [comment]
Actually, I used to create scriptableobject in a wrong way : I duplicate an existing one.
Now I use a script to properly create it.

It works. I think I did it the wrong way !
Sorry for  my misstake !

**Comment by vexe** [comment]
You could use the new Unity CreateAssetMenu, it saves you the hassle of doing it from script, you could just right click some where and create the asset http://docs.unity3d.com/ScriptReference/CreateAssetMenuAttribute.html
