### ISSUE TITLE
Serialized interface values turning into null.

### ISSUE THREAD

**Issue by LouisGameDev** [vexe/VFW#89]
[VFW Null Bug.zip](https://github.com/vexe/VFW/files/233216/VFW.Null.Bug.zip)

It seems that VFW can't handle the interfaces anymore. It is demonstrated in this project. Go into the project and click on Test Object, add the implementation into the list, run the project and watch it turn into null.

**Comment by vexe** [comment]
Yes, that is intentional. Interfaces are no longer supported. (refer to https://github.com/vexe/VFW/issues/88)

**Comment by LouisGameDev** [comment]
Ok, I just read your other response. Maybe mark it as obsolete somehow? Thank you!!

**Comment by vexe** [comment]
Yes you are correct. I need to modify recursive drawer to ignore interface/abstract fields.
