### ISSUE TITLE
Property value is not saved

### ISSUE THREAD

**Issue by jineqbrainenergy** [vexe/VFW#91]
Hi Vexe
 I have the code looks like this

IMonster.cs

---

```
    [Serializable]
public class IMonster {
    public virtual void startAction () {}

}
```

---

StraightMonsterBehavior.cs

---

```
[Serializable]
public class StraightMonsterBehavior : IMonster {
    public string crashEffectName;

    [Show]
    public override void startAction() {
        Debug.Log ("here " + this.crashEffectName);
    }

    public IEnumerator updateAction() {
        yield return new WaitForSeconds(1);
        Debug.Log("do nothign");
    }

    public void endAction() {
    }
}
```

---

MonsterController.cs

---

```
public class MonsterController : BaseBehaviour {
     public IMonster monsterBehavior;

    void Start() {
        this.monsterBehavior.startAction();
    }
}
```

---

In the inspector, I selected StraightMonsterBehavior as the value of monsterBehavior
then settled crashEffectName.  it works well till here.
But when I played, the value became Monster

I would like to know What mistakes I did? or I missunderstood on how to use your plugins?

Thank you

**Comment by jineqbrainenergy** [comment]
Hi Vexe

I made use of BaseScriptableObject, and solved my problems

Thank you for the great plugins

**Comment by vexe** [comment]
Hey there, did you read https://github.com/vexe/VFW/issues/88 ? custom serialization is no longer supported.

**Comment by jineqbrainenergy** [comment]
Hi Vexe.

Ive created something like this...

https://www.youtube.com/watch?v=KYgcjuuw6ds

to manage my SKILL objects, 
which contain a lot of actions(abstractions) 
such as: "Move Toward Enemy" or "Spawn Attack Effect(Kamehameha :D )".
your helpers are surely handy for that.

By made use of ScriptableObject.
I can also drag my custom SKILL objects into the scene for easier to debug.
But seem like it is slow as u mentioned, during editing.

I've learned my lessons.
Thank you.
