### ISSUE TITLE
RegisterCustomDrawerExample.cs is missed

### ISSUE THREAD

**Issue by bagobor** [vexe/VFW#94]
Hello, 

I looking how to customize drawing of member field and it look like you haven't push that file.
Without it CustomDrawer example is not complete.

Thanks!

**Comment by laicasaane** [comment]
Isn't it here?

[Assets/VFW Examples/Editor/RegisterCustomDrawerExample.cs](https://github.com/vexe/VFW/blob/master/Assets/VFW%20Examples/Editor/RegisterCustomDrawerExample.cs)

**Comment by bagobor** [comment]
Thanks for pointing it! 👍  ... it looks like I'm blind ... sorry for lame question. (before that I tried all search queries and nothing was found.)
